CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL IDENTITY PRIMARY KEY,
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	[UserName] NVARCHAR(50) NULL,
	[Password] NVARCHAR(50) NOT NULL,
	[AgendaId] INT,
	CONSTRAINT [FK_AgendaUser] FOREIGN KEY (AgendaId) REFERENCES Agenda(Id)
)
